Feature/update credits
oneleif/BunnyHopMaster pull request #79
Opened 2020-07-06 20:51 UTC by ambid17

also added unusualcrow's "urgency" soundtrack

2020-07-07 15:05 UTC, 0xLeif commented
When/ Why are the tests failing? :(

2020-07-07 15:05 UTC, 0xLeif requested changes
Tiny changes

2020-07-07 15:05 UTC, 0xLeif commented on BunnyHopMaster/Assets/Scenes/Credits.unity
> +    Chung ( Solstice_oo)
`(Solstice_oo)`

2020-07-07 15:05 UTC, 0xLeif commented on BunnyHopMaster/Assets/Scenes/Credits.unity
> +    Daniel Lin ( Chum)
`(Chum)`

2020-07-07 21:03 UTC, ambid17 commented on BunnyHopMaster/Assets/Scenes/Credits.unity
> +    Daniel Lin ( Chum)
ope ty

2020-07-08 05:34 UTC, Vextin approved these changes

2020-07-08 11:56 UTC, 0xLeif approved these changes

2020-07-08 21:18 UTC, merged